apiVersion: v1
description: A Hashicorp Vault chart for Kubernetes
name: vault
version: 0.2.0
keywords: [hashicorp, vault, secret, consul]
icon: https://raw.githubusercontent.com/docker-library/docs/726714ced14b1e14b6dd99fc82f20f14f1d3cfb1/vault/logo.png
sources:
  - https://github.com/hashicorp/vault
  - https://github.com/hashicorp/consul
  - https://github.com/djenriquez/vault-ui
  - https://github.com/bartlettc/docker-kubectl
  - https://github.com/bartlettc/omgwtfssl-kubernetes
  - https://github.com/bartlettc/letsencrypt-acm:kubernetes
  - https://github.com/thorix/consul-backup
  - https://github.com/helm/charts/tree/master/incubator/vault
  - https://github.com/hashicorp/consul-helm
maintainers:
  - name: Ryan Wilcox
    email: ryan.wilcox@readytalk.com
  - name: Chris Bartlett
    email: christopher.bartlett@readytalk.com
contributors:
  - name: Miroslav E. Hadzhiev
    email: miroslav.hadzhiev@gmail.com
