{{- if .Values.Vault.AutoUnseal }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "vault.fullname" . }}-vault-keys
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "vault.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Vault.ComponentName }}"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "100"
type: Opaque
data:
  key1: {{ "foo" | b64enc }}
{{- end }}
