{{- if and (not .Values.Vault.Tls.CertManager.Enabled) (not .Values.Vault.Tls.CertString) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "vault.fullname" . }}-{{.Values.Vault.PreInstall.ComponentName}}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "vault.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Vault.PreInstall.ComponentName }}"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "100"
spec:
  activeDeadlineSeconds: {{.Values.Vault.PreInstall.JobDeadline}}
  template:
    metadata:
      name: {{ template "vault.fullname" . }}-{{.Values.Vault.PreInstall.ComponentName}}
      labels:
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: {{ template "vault.chart" . }}
        component: "{{ .Release.Name }}-{{.Values.Vault.PreInstall.ComponentName}}"
    spec:
      restartPolicy: Never
      serviceAccount: {{ if .Values.rbac.create }}{{ template "vault.preinstall.fullname" . }}{{ else }}default{{ end }}
      containers:
      - name: {{ template "vault.fullname" . }}-{{.Values.Vault.PreInstall.ComponentName}}
        image: "{{.Values.Misc.omgwtfssl.Image}}:{{.Values.Misc.omgwtfssl.ImageTag}}"
        imagePullPolicy: "Always"
        env:
          - name: CA_EXPIRE
            value: "60"
          - name: SSL_EXPIRE
            value: "60"
          - name: SSL_IP
            value: "127.0.0.1"
          - name: SSL_SUBJECT
            value: "{{.Values.Vault.Tls.ServerName}}"
          - name: SSL_DNS
            value: "{{.Values.Vault.Tls.AlternateServerNames}},{{- .Release.Name -}}.{{- .Release.Namespace -}}.svc.cluster.local"
          - name: SILENT
            value: "true"
          - name: K8S_SECRET_NAME
            value: "{{ template "vault.fullname" . }}.tls"
          - name: K8S_SECRET_SEPARATE_CA
            value: "true"
          - name: K8S_SECRET_LABELS
            value: "heritage={{ .Release.Service }} release={{ .Release.Name }} chart={{ template "vault.chart" . }} component={{ .Release.Name }}-{{.Values.Vault.PreInstall.ComponentName}}"
{{- end }}
