{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ template "vault.certReloader.fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "vault.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Vault.ComponentName }}"
rules:
  - apiGroups:
      - ""
    resources:
      - "pods/exec"
    verbs:
      - "create"
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
      - get
{{- end -}}
